spring:
  datasource:
    username: root
    password: Ap3xt9qm@2019
    jdbc-url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
